### ISSUE TITLE
Fun fact: dyslexic font in night mode is mostly renderered black/dark (invisible), other fonts okay.

### ISSUE THREAD

**Issue by danielweck** [readium/readium-css#56] opened 2019-01-03 17:20 UTC
OpenType issue?
Chromium-specific? (reproducible with `r2-testapp-js` and `readium-desktop`, I haven't tried elsewhere)
Book/CSS-specific? (Screenshots below with "Accessible EPUB3")

...to be determined.

![screenshot 2019-01-03 at 17 16 19](https://user-images.githubusercontent.com/625201/50651524-919eac80-0f7b-11e9-888e-282f84c8e92f.png)

![screenshot 2019-01-03 at 17 17 39](https://user-images.githubusercontent.com/625201/50651527-919eac80-0f7b-11e9-8bdb-2b04a7905114.png)

**Comment by JayPanoz** [comment] 2019-01-03 18:04
Hmmm hmmm hmmm thanks for reporting that. After a quick check, there’s nothing related to colours in the [a11y-font submodule](https://github.com/readium/readium-css/blob/master/css/src/modules/user-settings-submodules/ReadiumCSS-a11yFont_pref.css) so this is kinda weird, especially as headings and code are inverted properly. 

Kinda reminds me of an issue I encountered with a KePub file some months ago though, that I didn’t consequently flagged as an issue because well, there’s extra markup + JS specific to Kobo apps/devices in those files. Still this one is weird because it only happens with the dys font. 

If possible, could you also provide debug tools’ applied styles panel, even if in the form of a screenshot?* Not the computed styles, just the applied one in order to get a sense of the cascade and how stylesheets interact there. 

\* I should probably add that in the issue template as it can help quite tremendously and often save a lot of time trying to reproduce it.

**Comment by danielweck** [comment] 2019-01-23 20:55
Related commit: https://github.com/readium/readium-css/compare/051e3d2d1842...1b8ba98a8704

**Comment by danielweck** [comment] 2019-01-23 21:07
Bug confirmed using the "font testing tool" with the new "night mode" switch:
https://readium.org/readium-css/docs/utils/Typeface-tester.html
(screenshots below)

**Comment by danielweck** [comment] 2019-01-23 21:07
Normal mode (green oval annotation added by me):

![readiumcss_accessibledfa_nightmode_1](https://user-images.githubusercontent.com/625201/51637151-e6b65880-1f52-11e9-896f-d4311c06286a.png)

**Comment by danielweck** [comment] 2019-01-23 21:08
Night mode (green oval annotation added by me):

![readiumcss_accessibledfa_nightmode_2](https://user-images.githubusercontent.com/625201/51637182-f7ff6500-1f52-11e9-84d5-ff3712666d1b.png)

**Comment by JayPanoz** [comment] 2019-01-23 21:12
Thanks for testing that before I could do. 

So that’s kinda insane, I’ve never seen a bug like this one. 

I’ll file the issue in the Orange repo ASAP. In the meantime I guess using OpenDyslexic as a replacement would be the best option.

**Comment by danielweck** [comment] 2019-01-23 21:18
Here is a reduced test case (in the second paragraph, the text color should be red, it remains black):
```html
<html>
<head>
<style>
@font-face {
  font-family: AccessibleDfA;
  font-style: normal;
  font-weight: normal;
  src: local("AccessibleDfA"),
    url("https://github.com/Orange-OpenSource/font-accessible-dfa/raw/master/All%20Fonts/AccessibleDfA.otf") format("opentype");
}
</style>
</head>
<body style="font-family: AccessibleDfA;">
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
</p>
<hr>
<p style="color: red;">
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
</p>
</body>
</html>
```

**Comment by danielweck** [comment] 2019-01-23 21:20
Clickable URL (same HTML content as above, base64-encoded):
data:text/html;base64,PGh0bWw+CjxoZWFkPgo8c3R5bGU+CkBmb250LWZhY2UgewogIGZvbnQtZmFtaWx5OiBBY2Nlc3NpYmxlRGZBOwogIGZvbnQtc3R5bGU6IG5vcm1hbDsKICBmb250LXdlaWdodDogbm9ybWFsOwogIHNyYzogbG9jYWwoIkFjY2Vzc2libGVEZkEiKSwKICAgIHVybCgiaHR0cHM6Ly9naXRodWIuY29tL09yYW5nZS1PcGVuU291cmNlL2ZvbnQtYWNjZXNzaWJsZS1kZmEvcmF3L21hc3Rlci9BbGwlMjBGb250cy9BY2Nlc3NpYmxlRGZBLm90ZiIpIGZvcm1hdCgib3BlbnR5cGUiKTsKfQo8L3N0eWxlPgo8L2hlYWQ+Cjxib2R5IHN0eWxlPSJmb250LWZhbWlseTogQWNjZXNzaWJsZURmQTsiPgo8cD4KTG9yZW0gaXBzdW0gZG9sb3Igc2l0IGFtZXQsIGNvbnNlY3RldHVyIGFkaXBpc2NpbmcgZWxpdCwgc2VkIGRvIGVpdXNtb2QgdGVtcG9yIGluY2lkaWR1bnQgdXQgbGFib3JlIGV0IGRvbG9yZSBtYWduYSBhbGlxdWEuIFV0IGVuaW0gYWQgbWluaW0gdmVuaWFtLCBxdWlzIG5vc3RydWQgZXhlcmNpdGF0aW9uIHVsbGFtY28gbGFib3JpcyBuaXNpIHV0IGFsaXF1aXAgZXggZWEgY29tbW9kbyBjb25zZXF1YXQuIER1aXMgYXV0ZSBpcnVyZSBkb2xvciBpbiByZXByZWhlbmRlcml0IGluIHZvbHVwdGF0ZSB2ZWxpdCBlc3NlIGNpbGx1bSBkb2xvcmUgZXUgZnVnaWF0IG51bGxhIHBhcmlhdHVyLiBFeGNlcHRldXIgc2ludCBvY2NhZWNhdCBjdXBpZGF0YXQgbm9uIHByb2lkZW50LCBzdW50IGluIGN1bHBhIHF1aSBvZmZpY2lhIGRlc2VydW50IG1vbGxpdCBhbmltIGlkIGVzdCBsYWJvcnVtCjwvcD4KPGhyPgo8cCBzdHlsZT0iY29sb3I6IHJlZDsiPgpMb3JlbSBpcHN1bSBkb2xvciBzaXQgYW1ldCwgY29uc2VjdGV0dXIgYWRpcGlzY2luZyBlbGl0LCBzZWQgZG8gZWl1c21vZCB0ZW1wb3IgaW5jaWRpZHVudCB1dCBsYWJvcmUgZXQgZG9sb3JlIG1hZ25hIGFsaXF1YS4gVXQgZW5pbSBhZCBtaW5pbSB2ZW5pYW0sIHF1aXMgbm9zdHJ1ZCBleGVyY2l0YXRpb24gdWxsYW1jbyBsYWJvcmlzIG5pc2kgdXQgYWxpcXVpcCBleCBlYSBjb21tb2RvIGNvbnNlcXVhdC4gRHVpcyBhdXRlIGlydXJlIGRvbG9yIGluIHJlcHJlaGVuZGVyaXQgaW4gdm9sdXB0YXRlIHZlbGl0IGVzc2UgY2lsbHVtIGRvbG9yZSBldSBmdWdpYXQgbnVsbGEgcGFyaWF0dXIuIEV4Y2VwdGV1ciBzaW50IG9jY2FlY2F0IGN1cGlkYXRhdCBub24gcHJvaWRlbnQsIHN1bnQgaW4gY3VscGEgcXVpIG9mZmljaWEgZGVzZXJ1bnQgbW9sbGl0IGFuaW0gaWQgZXN0IGxhYm9ydW0KPC9wPgo8L2JvZHk+CjwvaHRtbD4=

**Comment by danielweck** [comment] 2019-01-23 21:22
I logged an issue here:
https://github.com/Orange-OpenSource/font-accessible-dfa/issues/2

**Comment by danielweck** [comment] 2019-01-23 21:44
Yes, MacOS Mojave `10.14.2`.

Have you tried the reduced test case? (HTML snippet / `data:` URL)
Are you able to reproduce the bug in all web browsers but WebKit/Safari?

**Comment by danielweck** [comment] 2019-01-23 21:48
By the way, the test above is with the OTF deliverable, but I am able to reproduce with the TTF and WOFF variants too.

https://github.com/Orange-OpenSource/font-accessible-dfa/tree/master/All%20Fonts

**Comment by JayPanoz** [comment] 2019-01-23 21:48
Yes, that was the reason why I was asking, sorry if that was unclear.

**Comment by JayPanoz** [comment] 2019-01-23 22:01
So after super quick testing I can report Safari won’t render local fonts that were installed by the user (Font Book > user fonts) but other browsers will without any issue. 

So that makes the Literata bug in #58 a system bug, at least to me. 

I’ll try to dig a little bit deeper as soon as possible, esp. `color` and non-local fonts.

**Comment by danielweck** [comment] 2019-01-23 22:09
Okay, I am being an idiot here (sorry it's late ...)
I forgot to remove `src: local("AccessibleDfA")` from the `@font-face` declaration ... trying again with the remote URLs.

**Comment by danielweck** [comment] 2019-01-23 22:12
Yeah, only Chrome fails, Safari and Firefox work with OTF, TTF and WOFF.

**Comment by JayPanoz** [comment] 2019-01-23 22:18
As a clarification, just to be sure. Here is how it fails for me in Safari when I say local fonts installed by the user so not even `src: local("font")` in that case: 

![capture d ecran 2019-01-23 a 23 13 42](https://user-images.githubusercontent.com/12599652/51640786-bf688700-1f64-11e9-9a2c-d6dd186e8c14.png)

Chrome + Firefox are OK. 

![capture d ecran 2019-01-23 a 23 16 05](https://user-images.githubusercontent.com/12599652/51640858-f9398d80-1f64-11e9-8140-dd7b4497c2af.png)

There’s definitely something wrong going on with local fonts (user-installed so double-click on fonts and then install in Font Book.app) on my machine.

**Comment by danielweck** [comment] 2019-01-23 22:34
Damn, after clearing the browser cache, removing the local font, dealing with CORS issues, and setting up an HTTPS test URL, ... I am not able to reproduce the bug. I have closed the other issue until we find out exactly how to reproduce the "bug" using a minimal reproducible test case. Sorry for the noise.
https://accessible-dfa-color.surge.sh/ReadiumCSS_AccessibleDFA_NightMode.html

**Comment by danielweck** [comment] 2019-01-23 22:37
Note that the originally-reported bug in the Readium2 "desktop" app (Electron/Chromium) still exists. I am just trying to create a more generic test.

**Comment by danielweck** [comment] 2019-01-23 23:02
Ah, so in `r2-testapp-js` (and `readium-desktop`) the font is loaded from this HTTPS URL:
`https://127.0.0.1:8000/readium-css/fonts/AccessibleDfA.otf`
(localhost NodeJS Express server, i.e. `r2-streamer-js` with a static route to the ReadiumCSS folder)

So, I ran a test by loading this very same font into the `iframe` / `webview` *host* (i.e. the main `index.html` of the Electron renderer process / Chromium window), by injecting this CSS snippet using the web inspector at runtime:

```
@font-face {
  font-family: AccessibleDfA;
  font-style: normal;
  font-weight: normal;
  src: local("AccessibleDfA"),
    url("https://127.0.0.1:8000/readium-css/fonts/AccessibleDfA.otf") format("opentype");
}
```
(effectively the same `@font-face` declaration used when ReadiumCSS is injected into EPUB HTML Content Documents)

...then I added this attribute using the web inspector to some text in the app's user interface:
`style="font-family: AccessibleDfA !important; color:  red; !important"`
...and the text is red as expected!

If I disable ReadiumCSS and manually inject the exact same above CSS snippet inside the DOM inside the hosted / embedded `webview`, then the text color remains black! Weird bug.

**Comment by danielweck** [comment] 2019-01-24 00:31
Okay, I found a workaround. `font-weight: bold` fixes the problem. Don't ask me why. Good night :)

**Comment by JayPanoz** [comment] 2019-01-24 14:04
Alright, I’ve done some extra research during breakfast (sorry couldn’t post this morning as I was involved in a project defence jury @ the University). 

@danielweck My best guess is that when you’ve been initially testing and Safari was OK, it didn’t use the local version of the font (user-installed) but the online fallback because – surprise! – Safari doesn’t render user-installed local fonts anymore due to fingerprinting/privacy concerns. 

See [this reddit thread](https://www.reddit.com/r/MacOS/comments/9jp5m3/psa_safari_12_disablednerfed_setting_custom_fonts/) and this [SO question](https://stackoverflow.com/questions/52692905/font-family-display-issue-in-safari-12-on-macos-mojave). There’s a lot more of such questions/thread in the wild but few with a technical background so listing the 2 most relevant. 

I do believe that we’d better trim the issue down to Chrome and Firefox. My plan right now is the following: 

1. check AccessibleDfa’s versions (local and online) so I’ll also give a deeper look at the fonts in FontForge to check metadata/hypothetical issues;
2. if both are the same version, I’m planning to check various fonts I have installed on my machine, in order to see if the issue is reproducible with other fonts.

Then I’ll improvise.

At best I can init that tonight.

> `font-weight: bold` fixes the problem

Wouldn’t that “create” an extrapolated weight of the (base) regular font as there isn’t any bold font available?

My worry is that clearly Apple has been changing something in Safari and they may well have modified how MacOS manages local fonts to enable that. If that’s the case, we should be aware, because that would basically prevent us from using `local` as `src`, just to be on the safe side of the fence.

**Comment by JayPanoz** [comment] 2019-01-24 20:00
@danielweck So I checked versions and we were lagging quite a little bit – we were @ `1.0001` while latest is @ `1.5`. 

I can confirm that after the latest version is installed locally, it’s working as expected in Chrome and Firefox (i.e. black/red).

That brings us back to one of the issues mentioned in #58 though: updating fonts regularly if we decide to embed them in RCSS itself.

**Comment by danielweck** [comment] 2019-01-28 09:56
Status update:
I downloaded the latest version of `AccessibleDfA.otf` from https://github.com/Orange-OpenSource/font-accessible-dfa/tree/master/All%20Fonts
...and I tested `r2-navigator-js` / `r2-testapp-js` with it: the bug still exists, i.e. the foreground colour does not change inside a `webview` of Electron 1.8.8 (Chromium `59.0.3071.115` https://github.com/electron/libchromiumcontent/blob/electron-1-8-x/VERSION ), unless `font-weight: bold` is applied (there might be other workarounds, but this one works).

I haven't tried more recent version of Electron/Chromium yet.

I haven't had time to retrofit this simple test inside an Electron app yet (`iframe`, not `webview` ... but I guess we should test both):
https://accessible-dfa-color.surge.sh/ReadiumCSS_AccessibleDFA_NightMode.html

**Comment by danielweck** [comment] 2023-02-02 13:34
fixed by https://github.com/readium/readium-css/pull/123
?

**Comment by mickael-menu** [comment] 2023-02-02 13:48
That does look very similar. Maybe they fixed the font a first time but forgot some glyphs like the comma.

**Comment by JayPanoz** [comment] 2024-04-18 08:37
I’m assuming #123 fixed this so closing the issue, unless it pops up again.

**Closed by JayPanoz** 2024-04-18 08:37 UTC
